version: '3'
services:
  backend:
    build: ./todo-django/Dockerfile
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
  frontend:
    build: ./todo-react/Dockerfile
    command: ["npm", "start"]
    ports:
      - "3000:3000"
    depends_on:
      - backend